### ISSUE TITLE
Pressing enter from the title field does strange stuff

### ISSUE THREAD

**Issue by kidGodzilla** [ScribbbleIO/scribbble#2]
If you create a new post, click edit to add a title, and then press enter after creating a title, I'd expect it to move to the writing / editing box below.

Instead, it breaks the post in some weird ways, and the post disappears from view, and it creates a new post or something, loses the information from the previous post, if it wasn't already saved.

https://user-images.githubusercontent.com/6320214/197579554-4b2bc9f2-248d-4500-b8a0-4d4d78190094.mov

**Comment by wardpoel** [comment]
Hey @kidGodzilla 

Thanks for reaching out, but I think your issue is related to [https://scribbble.co/](https://scribbble.co/). We are Scribbble.io
